name: Continuous Integration

on: [pull_request]

jobs:
  build:
    name: ci
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala: [2.12.12, 2.11.12]
    container:
      image: ucbbar/chisel3-tools
      options: --user github --entrypoint /bin/bash
    env:
      CONTAINER_HOME: /home/github

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
      - name: Cache Scala
        uses: coursier/cache-action@v5
      - name: Documentation (Scala 2.12 only)
        if: matrix.scala == '2.12.12'
        run: sbt ++${{ matrix.scala }} docs/mdoc
      - name: Test
        run: sbt ++${{ matrix.scala }} test
